name: Serv00 Auto Bypass

on:
  workflow_dispatch:

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run in Docker
      uses: addnab/docker-run-action@v3
      with:
        image: python:3.10-slim-buster
        options: >-
          -v ${{ github.workspace }}:/app
          -w /app
          --privileged
          -e DISPLAY=:99
        run: |
          # 安装系统依赖
          apt-get update && \
          apt-get install -y \
            xvfb \
            chromium \
            chromium-driver \
            tesseract-ocr \
            libgl1-mesa-glx

          # 安装Python依赖 (关键修复点)
          pip install --upgrade pip
          pip install --no-cache-dir \
            numpy==1.26.4 \
            opencv-python-headless==4.8.1.78 \
            undetected-chromedriver==3.5.5 \
            selenium==4.15.2 \
            pytesseract==0.3.10

          # 启动服务并运行
          Xvfb :99 -screen 0 1920x1080x24 &
          python S00_CK.py
