name: Serv00 AutoRegister

on:
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libgtk-3-0 \
          libnss3 \
          libxss1 \
          libasound2 \
          tesseract-ocr \
          tesseract-ocr-eng \
          chromium-chromedriver

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytesseract opencv-python-headless pillow

    - name: Run Xvfb
      run: Xvfb :99 -screen 0 1280x1024x24 >/dev/null 2>&1 &

    - name: Execute Script
      env:
        DISPLAY: :99
        TESSDATA_PREFIX: /usr/share/tesseract-ocr/4.00/tessdata
      run: |
        export PATH=$PATH:/usr/lib/chromium-browser/
        python S00_CK.py
