name: Serv00 Auto Bypass

on:
  workflow_dispatch:

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run in Docker
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu:22.04  # 改用新版Ubuntu镜像
        options: >-
          -v ${{ github.workspace }}:/app
          -w /app
          --privileged
          -e DISPLAY=:99
        run: |
          # 安装Chrome 120
          apt-get update && \
          apt-get install -y \
            wget \
            gnupg \
            xvfb \
            tesseract-ocr \
            libgl1-mesa-glx

          # 添加Google Chrome源
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
          apt-get update && \
          apt-get install -y google-chrome-stable=120.0.6099.224-1

          # 安装Python依赖
          apt-get install -y python3-pip && \
          pip install --no-cache-dir \
            undetected-chromedriver==3.5.5 \
            selenium==4.15.2 \
            opencv-python-headless==4.8.1.78 \
            numpy==1.26.4 \
            pytesseract==0.3.10

          # 启动服务并运行
          Xvfb :99 -screen 0 1920x1080x24 &
          python S00_CK.py
