# .github/workflows/serv00_auto.yml
name: Serv00 Account Creator

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: '启用调试模式 (true/false)'
        required: false
        default: 'false'

jobs:
  account_creation:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev libxshmfence-dev
        
    - name: Install Python packages
      run: |
        pip install DrissionPage==3.2.35 faker==18.11.2

    - name: Run automation
      run: python S00_CK.py --url=https://www.serv00.com/offer/create_new_account
      env:
        HEADLESS_MODE: 'true'


    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: serv00-screenshots
        path: |
          screenshot_*.png
          debug/*.png
