name: Serv00 Auto Bypass

on:
  workflow_dispatch:

jobs:
  bypass:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        # 强制重置软件源配置
        sudo rm -f /etc/apt/sources.list.d/*  # 清除第三方源
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu jammy main universe multiverse"  # 核心源
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse"
        sudo apt-get update -y
        
        # 安装必要依赖
        sudo apt-get install -y \
          xvfb \
          libgl1-mesa-glx \
          libxkbcommon0 \  # 新增关键依赖
          tesseract-ocr \
          tesseract-ocr-eng

    - name: Install Python packages
      run: |
        pip install undetected-chromedriver selenium opencv-python-headless pytesseract pillow

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1920x1080x24 &

    - name: Run script
      env:
        DISPLAY: :99
        UC_TELEMETRY: "no"
      run: |
        python S00_CK.py
