# .github/workflows/cf_test.yml
name: Cloudflare Test

on:
  workflow_dispatch:

jobs:
  test_cf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get install -y libgbm-dev
        pip install DrissionPage

    - name: Run test
      run: python test_cf.py

    - name: Upload screenshot
      uses: actions/upload-artifact@v3
      with:
        name: cf-screenshot
        path: screenshot.png
