name: Fetch cf_clearance Cookie

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次（UTC时间）
  workflow_dispatch:       # 允许手动触发

jobs:
  fetch-cookie:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install DrissionPage
        run: |
          python -m pip install --upgrade pip
          pip install DrissionPage

      - name: Check Microsoft Edge installation
        run: |
          where msedge
          if ($LASTEXITCODE -eq 0) { Write-Output "Microsoft Edge 已安装" } else { Write-Output "未找到 Microsoft Edge" }

      - name: Run script
        run: |
          python S00_CK.py

      - name: Save cookie to artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: cf_clearance_cookie
          path: cf_clearance.json

      - name: Commit and push changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cf_clearance.json
          git commit -m "Update cf_clearance cookie"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
