name: Serv00 Auto Bypass

on:
  workflow_dispatch:

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb tesseract-ocr tesseract-ocr-eng libtesseract-dev

    - name: Install Python packages
      run: |
        pip install undetected-chromedriver selenium opencv-python-headless pytesseract pillow

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1920x1080x24 &

    - name: Run script
      env:
        DISPLAY: :99
      run: python S00_CK.py
