name: Serv00 Auto Bypass

on:
  workflow_dispatch:

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        # 启用 universe 仓库
        sudo add-apt-repository -y universe
        sudo apt-get update -y
        
        # 安装核心依赖
        sudo apt-get install -y \
          xvfb \
          libgl1 \ 
          libglx0 \
          libxkbcommon0 \
          libx11-xcb1 \
          libgles2 \
          libegl1 \
          libgbm1 \
          libasound2 \
          tesseract-ocr \
          tesseract-ocr-eng

    - name: Install Python packages
      run: |
        pip install undetected-chromedriver selenium opencv-python-headless pytesseract pillow

    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1920x1080x24 &

    - name: Run script
      env:
        DISPLAY: :99
        UC_TELEMETRY: "no"
      run: |
        python S00_CK.py
