name: Fetch cf_clearance Cookie

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次（UTC时间）
  workflow_dispatch:       # 允许手动触发

jobs:
  fetch-cookie:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 与日志保持一致

      - name: Install DrissionPage
        run: |
          python -m pip install --upgrade pip
          pip install DrissionPage

      - name: Check Microsoft Edge installation
        shell: pwsh
        run: |
          $edgePath = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
          if (Test-Path $edgePath) {
            Write-Output "Microsoft Edge found at: $edgePath"
          } else {
            Write-Output "Microsoft Edge not found at default path"
            exit 1
          }

      - name: Run script
        shell: pwsh
        run: |
          python S00_CK.py

      - name: Save cookie to artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: cf_clearance_cookie
          path: cf_clearance.json

      - name: Commit and push changes
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cf_clearance.json
          git commit -m "Update cf_clearance cookie"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
