name: Serv00 Auto Bypass

on:
  workflow_dispatch:

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run with Chrome Docker
      uses: addnab/docker-run-action@v3
      with:
        image: seleniarm/standalone-chromium:120.0  # 指定稳定版本
        options: -v ${{ github.workspace }}:/app -w /app
        run: |
          apt-get update && apt-get install -y tesseract-ocr
          pip install undetected-chromedriver pytesseract opencv-python-headless
          python S00_CK.py
