# 更新后的serv00_auto.yml
name: Serv00 Cookie获取

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: '启用调试模式 (true/false)'
        required: false
        default: 'false'

jobs:
  cookie_fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgbm-dev \
          libxshmfence-dev \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libgtk-3-0 \
          libasound2

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install DrissionPage==4.0.23

    - name: Run automation
      run: |
        mkdir -p debug_screenshots
        python S00_CK.py --url=https://www.serv00.com/offer/create_new_account
      env:
        HEADLESS_MODE: 'true'

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cf-screenshots
        path: |
          debug_screenshots/*.png
