name: Cloudflare Bypass

on:
  workflow_dispatch:

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run in Docker
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu:22.04
        options: >-
          -v ${{ github.workspace }}:/app
          -w /app
          --privileged
          -e DISPLAY=:99
        run: |
          # 安装系统依赖
          apt-get update -y && \
          apt-get install -y \
            xvfb \
            chromium-browser \
            chromium-chromedriver \
            tesseract-ocr \
            libgl1-mesa-glx \
            python3.10 \
            python3.10-venv

          # 配置Python环境
          python3.10 -m venv /opt/venv
          . /opt/venv/bin/activate
          pip install --upgrade pip

          # 安装Python包
          pip install --no-cache-dir \
            undetected-chromedriver==3.5.5 \
            selenium==4.15.2 \
            opencv-python-headless==4.8.1.78 \
            numpy==1.26.4 \
            pytesseract==0.3.10

          # 启动服务并运行
          Xvfb :99 -screen 0 1920x1080x24 &
          python3.10 S00_CK.py
